import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

import Provider from '@/utils/provider';

import Header from '@/components/Header';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

const siteTitle = process.env.NEXT_PUBLIC_SITE_TITLE;

export const metadata: Metadata = {
	title: siteTitle,
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Provider>
					<Header />
					{children}
					<Footer />
				</Provider>
			</body>
		</html>
	);
}
